name: Test
on: [push, pull_request]

jobs:
  pest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.1, 8.0, 7.4 ]
        perfer: [stable]
    name: PHP-${{ matrix.php }}-${{ matrix.perfer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest --prefer-${{ matrix.perfer }}

      - name: Run Test
        run: composer test
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
